#!/bin/bash

# 🚀 Complete Expo Fix Script - Resolves all connection, asset, and auth issues
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

echo -e "${PURPLE}🚀 COMPLETE EXPO FIX - RESOLVING ALL ISSUES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. Fix Authentication Issue
echo -e "${BLUE}🔐 Step 1: Checking Expo Authentication${NC}"
if ! npx expo whoami >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠️ Not logged into Expo. Some features may require login.${NC}"
    echo -e "${BLUE}To login, run: npx expo login${NC}"
    echo ""
    
    # Create anonymous config for development
    echo -e "${BLUE}🔧 Setting up anonymous development mode...${NC}"
    cat > expo-anonymous.config.js << 'EOF'
const config = {
  ...require('./app.json').expo,
  extra: {
    ...require('./app.json').expo.extra,
    eas: {
      projectId: "anonymous-development"
    }
  },
  owner: undefined,
  slug: "local-clubhouse-dev"
};

module.exports = config;
EOF
else
    EXPO_USER=$(npx expo whoami)
    echo -e "${GREEN}✅ Logged in as: $EXPO_USER${NC}"
fi

# 2. Create Missing Assets
echo -e "${BLUE}🎨 Step 2: Creating Required Assets${NC}"
mkdir -p assets

# Check if assets already exist
if [ ! -f "assets/icon.png" ]; then
    echo "Creating default icon.png..."
    # Create a simple colored square as icon using base64
    base64 -d > assets/icon.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAApqSURBVHgB7d1NbttIGoDhL0mZTqfTnhVgn8A+gZMTJDlBkhMkOUGSEyQ5QZITxHOCOCeIcwLbG++ycbvbsihSVFX9PM8CCGZ6AXjx439VsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCU3AIzsL+/v7VcLrcXi8W9xWJxd/j7y/DPNxY/uloul2+Hv18sl8vz4e/nw9/Pzs7O3gIzIABSGA7424vF4sHwz/3hy3xz+LJff7Xrl4vhiz8Zvvjj5XJ5fHZ29jqgMgKgJDs7Ow+GL/lguVw+XPwY7K2Gm+HtEAOHQxQcnp6evgkoiAAo2RAGz4Yv++5ww98OKO9iCIN/hq//X0BhBEBJdnd3Hy0Wi+fDjf8soKazIQb+PDk5eRmQmQDIafiyfw5f+N+Gm38R0LTTIQT+ODk5+SsgAwGQ2u7u7m9DCLwYfvUngObT8EDy2ysLhRQEQEqbm5vfDDf+3wETd7FcLr87PDx8H5CAAEhheJr/YvjVfx7Ml88+DxHwOmBNAmAdw5P9vw+/+s8DcrgavgcfBaxIAKxqc3PzP8OXrxpnbldDCPx5cHDwPmBJAmAV29vbfw1f/v2ANlyp8y1NAEzVm+qfgw/DCcGLgAkEwBTDU/7D4YufBbTrn5OTk6cBIwiAMYZ2n7d9z5gCLIUIOD09fRbQQwD0Gdr93vY9Yx6wNG8LNgRAF+1+ZF8IREC/w2FhsBOwRgDcpN2P7C8Wi//SHtxNAFyn3Q9laQ/uIACuePqPJtoRIACGm//x8OX/X0BdtAcLgPm3+6kCpuHM4OTMOwDsepuGl0H3h9OB34X5me2JwfkGgKqfs5mJQM6mcgJwXgGg6iczyJCcUQjMJwBU/eQGOZLKCcD2A0DVT2kgT3JGITCPHQFzGfZxO6Ak88gJ5tEOXLeA39raeh9mZ6/rtjAFU6rqHlTqfAFgAChtqppBGAJaYKGqbgG1HQDDvv5z6/rRgOr3DLQdAAZ8mDgHyElaIdBuABjwYeJcHhPnJK0QaDMADPgwdTlwT5g418cpWiHQXgAY8EH1z8TFMQRUR0xDWwFgwAer/phYo1MLgXYCwIAP1jxiYs1OIQTaCABVP1j1h4kKQO5BoP4AUPWD6p+pNTy1atAHdQeAqh/s+mNqzU+tGgDqDQBVP6j+YaqAqgCqbgFrDQBVP6j+YYKgOqgOqgKosgWsLwDU/dhQTjBBVQ1U1QLWFQCqfmwoJ5ioygaqagHrCQBVv6p/oFuAiYJqoToQAAxU/Qp/mCiqF6rqA4YVAKp+A0Ap3AIwheFENtUCVtEH/BSQ3vb29vtQ9Q90CzBRdTxYC5CtBSwfAF782d/ffxsKf7AFYFUU/mVL2wIWDQBVv8IfJoiq6iXKGoC0BSgWAKp+r/rCRNGRdaVBWQFg119L9t5776V8u7Ozs7MXAQmkrQFKCgADPi1J+R5vb28/j09PT18GJJB2EKIUAOCG4Uf/fXx6enoQkEDygUgBwBTDrP/xEACHAQkIACZ6Ptz8b4YAOApIQAAwwaNhsOfZ8M93MRzBBQn4PjCFl35hYsIFSAAAAJMSMuADTEr4HgAAE7VQA5TzSfAEoLoAGOb+XwXAdJ0HgAAAgIkEANNqAYDJ0t8CNP5J8F1AZ7u7uy8CYFLid4HJawBVPzB58RtBCQCmOQtqsru7a/4fVib+dGABwDSNLgBa/YdVie8BBQAAdOgdAKp+oBXhe8CcNYCqH2hF+BogZwCo+lX9sHLxNUDOAFD1q/phteJrgJwBAABXZFkEzBUAWgBYsdhqxRfBXAGgBQBa0cgtQK4AaKQA5utTqPJdvh9KJZctQI4AUPWr+qE2WdaAcwSAql/VD7VZ6RYg5y1Ajm9Ci+8/NFP8oI9bgGn8+kNNMnx/BQAAdMgRAFoAoBXhW4AcAaAFAFoRvgWY+xZgCu8/1CTDGnB4AFD1A60IrwHCA0DVD7QivAYIDwBVP9CK0AAIDwCtxQCtCL0FCL0FaOSbkMvU/78vl8u7Mbzfw8///Z3hP11E7c/PLhaLxe3rd2j4b7djxM/v5YqLiYuBiwhchA2/BRAAlXCjA5PIshVYAADQgQCopgU4CIBJBEAFxn7xy+VyZwgBN3+/k5OTo4CJBECFzs7OXsfw5R8IgH4nJydHkT8A9vf3t0KB9vf3H8Tw5f85DPaUsVgsXp6dnb0OSGxtbevWIoHb/wjFOT4+/j6GL38IhY+xf/78+VnAZAJgJQJgCru7uy/i87LfdwGjnJ6enke+AFgul2FLQbchAIr15MmT28P7PYiP5//fhAGdEW6/fRsGU3/1Z3cL0J/d3d1nsRYGzxaLRcivDjf74+Xw38+Hv38Y/tvF8M+Li4uLj1dP/je5+K4b/u/9j3X5/q9e//d3h7/vxOdbmAfx+WOuhcG3mQJgZ2dne7lcfqv6b9jOzs6DGL78Z/HjzX9Vj3gxRMAihn/Gwf6rn4dxKVBa8fDhw5Ow2FuT3AHQXAH44MGDzbhU1Tf6v+v64t8MSfYphj//YRy1RbKmK38B4puvfxaXF1HtD3qxEgEwjrOASt2OAQBIK38N0P5ZgLFB2nUA1iUAqrcF1M9T9aNaAABiCYAO//79+5fD7cOjgGnOh9//9wEjCYAO9/Dhw4fxY3vxfqhkxvjvp0+f/hoGeoYX/1FAb4UGgDX/+JBwuN2f/f79+9MAeiw0AM6dBUy3dePP1wr8WBhYLvzjAwBw2ZU1YFVAZ4XOAvbz7u9PDx48+DGGbcABIxSaAKp+VUCHgJ2A9gkAgBBXCwABsKJ3Mdz8z549+zaAkQTA0p7Fp1+A7969+0NAI4p9JBAANRMANVsLFABA8coMAD/c7bDdkVaVGQCGNtphuyOtKvMhANBYBSj8S3P9B9WQT/G3AJTi9OnTp3c7/s/vA6jEcrmslgBYz9evX38KYCK3AAAhyk0AAVAXn/YwmQAAgA4CgKqo/llGsAIzIH0L4B+/Hur+hl1ZrBMALRuCeRHDvQHQqMgpQNUPoSsAcXNCAuCmgJwEQN0JkJQWYCWdITAEQNgCDu8BSQIApijzISDL8wRsZHhhQw7MU5m3AJGRAqA9AqByJydRBcD19zw7OzsKoFFRHwJwA9COQkbLBQAAjSo0ASgqBEpZBBxjsVjsZvgQxK1btzYvLi6+iWGCb7lc7oZBoL5/WiWz5RqZNBABZQVAQSFg0Kff9vb248ViMbz420MA3I8fDv7sXvv3d+YQBRcXFz/E8FFYLhaLo+Vy+ebz589/B6xJ1rOsxRcDf/4VAOArEEOVDPigBcCQD0ALsq8BlhmAh4dvA2AxAwBgOgHAUvPf/gO4KgZAuQxbgQHgsjwJUHACGL7J7gLgHAUngAAgB8HdkqI/BdD8J8D29vb7AJjGRyAJAGCMcp8OLQAAQjQaAKYAAUJYBASADo0GgJ9uAAjR5kOAu7u7jws/Bfh9ADRoOIF7J6B2xS8CCgCgRQIAADoIAIA5EQBkfQhwGQAt+j8iA3AKCIcgXQAAAABJRU5ErkJggg==
EOF
fi

if [ ! -f "assets/splash.png" ]; then
    echo "Creating default splash.png..."
    # Create splash screen (larger blue square)
    base64 -d > assets/splash.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAABLAAAASwCAYAAADrIbPPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABNbSURBVHgB7d1BbttIGoDhvyhZTqfTnhVgn8A+gZMTJDlBkhMkOUGSEyQ5QZITxHOCOCeIcwLbG++ycbvbsihSVFX9PM8CCGZ6AXjx439VsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCTNjc3724tFoudu7u7W1tbW9vLG+7s7GxtbW3dGq43/N3L5fLu8t+3l7+3vfznzfj873eW/3x7+e9ubm5u3YytrS03DgAAAAAANu3z58/ny+Xi/OfPnxfL5eL88+fPF8t/Xi7/ebH853mxWCwuLi4uzpfLxfnV68s/X1xcXFwsf3e+/LuL5XJxcXFxcRGQ1NbW1tbNzc27u7u7d7a3t7du3v3799vb29u3lsvFre3t7VvLG27dunVr+c/by3/e2t3dvbX85827d+9u3bx79+7Wzbt3724LAJ7bXhYAAFCjy8rV1tbW7d3d3dvb29u3d3Z2bi//3Ll79+7t3d3d2zs7O7eXP3d2d3dvL39u7+zs3F4ulzs3NzeXBRcAABTu8ePHW8vlcufevXu7u7u7u5vL39vZ3d3d3dra2tq9ubm5e/Pmzd3d3d3d3d3d3a2trd3lcrm7uVwud27evLm7XC539/b2dpfL5e7Ozs7O1vLnd+/e3dnd3d1dLpe7t27d2llWXneWy+XOzs7OznK53Nne3t5ZLpc7y39ub21tbd28efPmcrncGp7L/3+5XG4t/99be3t7W8vlcuvu3btbFxcXW8vlcmu5XG7t7u5uLZfLreVyubX82dre3t5aLhdby7/fWi4XW8u/31r+3dbyn1vLn81hIfKqBQBQs+XNvru7uxsQAwCgXMsKa2uxWGwt/7m17KLZXP7zcvlza/nz5t27dzeXP28u/762l3+/ufz7zeXfby5/bi7/vrlcLjaX/35z+feby7/fXP5sc3hev8e29va2FsOqvAAASlFXANy8efPm8jrL6uvy8vy5+frz/Pz86ve+fPny++//+OOPP5e/8+cff/zxx/Lnz+Xy519//fXn8uevX7/+Wf7+n8vl8s/lz5/L5fLPcrnYurZcLG9e/s5iubiI5e1gvQCrqSsAqqcFAAD+ZTiCAwCAOggAAKCHAACAcm0GAACJvH///qpNGQDgFQQAAKR0enpqUxaAV7DjEQAAAADokS8A9AIAAMCKBEAyAKYArcOgMABEsQkgGQEAAFGlnwGQt0sBAAAIJgCYxsKgFmAVBYeQXAUALQJw/TYAJCMAACAKp4+ZJqVcFAAApCIAAPqp/pmmpQRAwlwUACRjAsDCINNYmGWalHJRAAAAwxgwAJimhLfVAgAAYhEAAFA66wBMlXJdQABMYzEIAGCQfAGgBQAAmCBnAADANOn3AAiAnvf39/f39/f39vb29vb29o5PT08PG5K3ACgqAA4PDw8bCiQSAEKp/pkmJQLaSwBTAJi9FgaAaUpIgLJG+gHgXVT//Mvy36pqAKKwCQAA6GVz1DQl7AwQADwTMX8LTAFaRwmvKwGQ92QCiKT6v0Yh1T/HVGtqAAAAjJDzYiCAPlPe1gMATCcAAICxBEBO7gTLKyG3AJhOAAAAQB0aKgAAAICMBEAyIqGd1iTA9GGqlG8rAZCP15VTrATAyAgxJqOcQQEpSQGKDQG+c1wLAAB9KgwBAUCfEoowQnEcFOIQJIJFvOQOAOJnx+7u7t7u7u5jV1rbtOyOEqJMUBBMUsJrSQCQUm1HqbZ2nO1YNMYAQL0CdAbQcHx8PJsP/PT09GBvb+9xE3P9y3/cRCUagOKk3NlAAJQdAUeNe/78OdvJEQD9Kv3vTXJaAKJ4TQUyBTjvFgBAoX+d9gGgvEcBeC0FABVoYQpw+s8LAAAAAFCGOj4BaElKOURxHJUJQIlqKYCStASEAAC4KgIBAEBJXLwBAESzfOsGQH2KCADLEbUdcgAAKOT7RgCA8jV0CALAJiQfK1F4AAAAAAAAAEAYLYDXVdoTxgAAmKcapgCtJTJVSSvYBgIkl3LOHU4AABSlpZ0PJMjJhgKAAQAAQJfSC6KSIyBHAFSWQlAXFQAAkFgdhyAALOW9vQAAAGjC1BNAW5sCtJ4LxfLhCKArAAAtGQAAmJTkzwABQJFaLgBa2yGRIMcaGBfJJGUEQOsvJQBoRW0FgPUDAPKW1MU/BAigGJAuACo5AUEuwgAgC1sAABjOwQcgr6B+xQVAAqOLWQCAOQ8Uo7TP8SVDAADA/LgAAQBqJQAAAACq0MQJCF3U9jIbAQAAJdICAJRcGSU8BSPQZCMAKsn8vb29vb29x4+z3FqSs8AucZ1iM5MAAABQBgEAAEylI0a8SX8QnoCOAAEQgJAAAMiWjJsBEfJfBw0EQL4RDzXh9Hfm7fT0dCYxDQBAHJUdgJBCCx9xKgAAAGiKAAAiswJZS2mzaYUf8gIAsIrKCgAAWJl9BxROAEB9TERYxx4A4A1TLz7mAE/t7Ow8zZUG9UkekfkvEJcA2AAAoLJA5wJlS9wBAGhhEQCcvKcBAGTRQgBE/ehzJsBMFpAAACZaowAQACQsNgQAAFCCqp4BAAAAAAAAAMCsSgABUJMZBBAA8CZLNwBQBAEAAEC+xCEugF5XxxRgpbVupuOZ8j8AAFgDc1ICQHvJBBqUaQqgBIihxNO1hFECMIBJDgCgKNYAQmoiAFIu0kPZcnfGAjBSCRdpAZDsFBQBwEAWYEu/BgGwXkkHAPEJAODvKg+AtgKg7+Q4PDw8bOJzOT09PUhQQPfGMgCwLgKgJRE/Y4B4bAKAMSkJADH4YHJxXgAAAABQAx0AAABANQQAAADAHNgDANBPAAC0xXlRUCQBAABzlOgU1AKQxMoOgNrOS5MQtR3mCQBQJgEA9BSxAFCS2gJAAJCMAABYgywCgCEEQFMAaHm8Tqlzc3JycnJyclIBAQAlKnEKoMdCCuQT4AQ0OU5OAIC06goARQQAJKcAANoh7AEAmJMGCgAAAACmyRYAAAAAAKAXCEIJAAAAgCJoAQCgaJUFgJO3rWZLm8AAQOPqCIDOKcDdXJwCdCsBcCsAACBoKUGBBhBJRwAAMCsNnP4AQAJlBwAHJycnJycnJ3Vb1LpJJyOXGQA9BUBrVdZM3xAAkFBdAaCIAIAkBACsY2dnZ9NVElUraQGqsn8AQBb2AMBCZQAAMKsRABQpewAAAEAOAgAAKELiABgNDcBQOQOg/zHPOQWAuJaLQBMFQG0HJBRwnKcAqJsAAAD6NBwA0NcC0MIm2CihCMArCQAAAGpjDwAVjNSzOQJmTAAArKVcAUDNXCyVAwALy9xDqxkAAAAEoAMAYCg3a4BQBEDJBIBOBABg1poIAACoRO0B0HXN4xAgQRW9MUoAcLXZEAAEIgBaQAAkrAUAKFqmAAAAgKJkCwAAiKDsBfNh6/ypRu0BYC+AJoI5V9zzTQFaCAD1BECZBAAArHJKAABTxU0DwVxYBOStBIBABQBgJAAKIQDIQgAAEJEpwBFaOIGqTAAAlGDqOQAAMJYAqMvJycncpwCGAsDeAgAgBgEAtb+9AQAAgAy0APSS7jMRAFGyAFjBpNgAgBUJAAAgkgVgHp6BSvROKPCRSwDs7e3t7e3tNR4ACYCRAqDhEAAoQKYpAHnVtQdATvn8pMECAMgMAKAUPkwAgDxqCwAAmJi5DQeAAID5a+0qOxsCoNIAAACodQoAAMCslBwAAAAAbAAAsJoZAJAA6K5wCYBwCWjlSQDQSQAAAEAMAAAom8VgJslbhAgAAAAgQzUy5xJAACjgAQAgBwFAJgRAAAAUxtQjAFlTBmrlYACmpGELAQAAUAABAECNxBQAQGlqCwCf7SzmAADA2rQcBAAAbKj0AAAQ0gRX/WnAAP/K9EEKAEIQ5kDJShJJAAA8N4MAAADGKjkAkgYAAADMV6UBAABAEyoNAIrZAwDApNBOEAAAQNZ0/lQBAFqoiNiQsZBIJIUIX/9LBgBrGQwBAJHIagAAgFrYAwAAAAAAAAwjAJKR+dE1EX9OT08PGgAApipZWQHQ0xIg1wHABQsAAJCFACC7hJEBXa2tgwAAFKKZAIjCKUBPSzGOLBOJAMRXWwC0cArJAABQNy0AAFc0FAAAsJ7sAQAArauuAGgAAAAAgBkRAAAAANXo/I4bOEq7AIC1CAAAgDmqLVY5+RQaAABAWWyjp8lcBBYxnDFDEAAAAFS5BwCAQZFBBZJu5gEomQAAaBqn7wGURAAAQGPcSwAaBo8BAAA9AGg+AAAgQyGStwWoLQAAaE5tAQAAADARKkgAAAAAAABQEgEAAAAAsRQxRSoAqIBAAgC4lgBo6YABAAAgitIDYHNzc/Pw8PDwIJGqAyDla3VjY2Pj9PDw8IAAIBQBADCUUCIvAbC+w8NDu8IzODw8PLhxcnJyogAguaoDIN0J3vJ9t7KzJiIAGEEAAGQlAAAAIJJMAVBJBN+yB+D5IQhHCQJAAKStaZPdnImI7xvKJQDSBQAAwCvNuQQoIQBiDgBKVgAYMxkAAEAR8gUAAICOAABoMwAAAAAYRg8ABAAAAFC6uQcAAMCsCAAAYI5qOgQhb8DknQJU8g0AqIC7LADpCAAACiMAAAAACMNOAAC4zhycAJhOAgCglBrFHVcEAKyhZJEAABjD9mMAyGdxEQBQNlOAABBXS+MXASgA4EpLAQAAAAAAAECXqgNAOFdGwxVQASE5Czcg7/1+BNbgdQQAAEwkAACAOerJkJRTgKoDAABqU0IAAAD0EQAAwHTrDfG9/gRAqAAQADQRABEVnQAtbP8AgEQEAAAAAHMfAJRAAADwuugAeB4yAABdBAAAAAAVBIA2QEsuAsC9H1ag5xCARLcb21xTaC0AWnp7CAAgABLdEeI/A9z2AACIQgAAAAAAQJGaCQAAgBKkDAAVpAAYFgCOSQPgRcQ8AKJsNmT/BICFrPfm4hCA5Lnw/P1YfwHsLQAAEIU9ALOvhWI99wA5VwCzIABYhQAAAIDr5BwAAABcAqArJlMAyKJlLwAAaJQAYAILBAAAUAABwAQCgJkRANBJAMA1xvD7b87+XpxXCLCZJ27JQgCwQAAAsLFhAAAAAABQDgEAAADEkkUAWCBd/wQsDUNfOwIAgGoIAGokAIDW2ENFBwEAADzj1JVEBEAxQu/sWIeFAACAjZSThQ0DADSNYo2gAJjDFGBOeTDDBqt7nWFpAEIy5ogPAAAAZiUAIM9yqHy7jgIAJhU2LQQA66OdEQBaJQAAoGCJFyeTPQN6SzsBsBoBAAAwR5kCoIqDbJP+ZQBQNQEAAJRt6gKoHJYAc5AAiCT1CcDrEgDBAsC5CrB3F+rXRFJQ7NXBUi9lEgBUJOdD0NpzAABl0wMAAOVo4BCEOgIAAKAyAqAImgEBAErj4JVEBEDf9b/+QAAA+HcXFxcXAQjAAAAAehkDAOXy0iI6K5MAFJJXWnT6vG0KwG7ABhNgDAEAc6YFAQCKJgAAlqoYA8QgAABo3dTPf0YKegBJCQAAAGpR5RQgrJUIAAAoTQsBQOlKCAAaKABKn+wDQBACAAAo3cpTgFUIAABonAAA6CMASEdnSggCgJFGxpMhEgAAAABpCQCAAERiGgAAQJgWSwsAAAA0qbcHoKQAAAAAoJcAAAAAAEhKAACAJRAAKiYAyL5G7DsE0LJSBiYa9gQAgAgA6hS9AKiFQg4AAIgh3xRAANhDAAAAAAAAAABoQhcBUJGKEgCgP5MBgDcSAAAwlMPvAQAqYg8AAJNiIjAAeEsBMGn4IgAAgFZNKqIFAAATOQqZJgGQRAAA5BxSCwDiEwAAUCwBAEDf9Q8AAIrwpimAfB8ARIQRAJNUEADedwDEkC8AQn0ALKEAWFONAQBv1OsDqKTLJHQA1Lh4AEQkAEIFQLBZnAAAgJksLioJgCoWD+7u7u41AAAABTIcBNaXbQrAA+1s7wEhCQBaYVgNAKwu5RRgqgDoOgAAIKEqAsB3DQAEIQAAAGC+6goAaAahBEBJBzJOqQCYLgCaOAQBAAAAICABAEAJ5AMAqzq5AAAAAGjKnAMAQHi7eQEAAABA0QQAAOQmAwAgAy0AULCeBFAAcINJW4AqAjhvyoq0hEBCU+NDKcxaOzb39x/v7u4e5woAjCcCxmxdl3iT1cCxCQCMFQBAFgJg4NZ17xsAZhwAsA6vIwAAAAASEgBNLQAAzJnvJ8BLg6YATfmvHm+oJO/oH1d4z1EEgPsCAMCrSAAARDsAEgDmrKUCYOxLlLkQZ5EOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACN+v8ACjYGXQ6pWqgAAAAASUVORK5CYII=
EOF
fi

if [ ! -f "assets/adaptive-icon.png" ]; then
    echo "Copying icon as adaptive-icon..."
    cp assets/icon.png assets/adaptive-icon.png
fi

if [ ! -f "assets/favicon.png" ]; then
    echo "Copying icon as favicon..."
    cp assets/icon.png assets/favicon.png
fi

echo -e "${GREEN}✅ Assets directory created with default images${NC}"
ls -la assets/

# 3. Fix Metro Configuration for Better Stability
echo -e "${BLUE}⚙️ Step 3: Optimizing Metro Configuration${NC}"
cat > metro.config.js << 'EOF'
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

// Basic configuration without problematic options
config.watchFolders = [__dirname];
config.resolver.platforms = ['ios', 'android', 'native', 'web'];

// Increase timeout for slow connections
config.server = {
  ...config.server,
  enhanceMiddleware: (middleware) => {
    return (req, res, next) => {
      // Increase timeout for all requests
      res.setTimeout(300000); // 5 minutes
      return middleware(req, res, next);
    };
  },
};

// Optimize transformer for stability
config.transformer = {
  ...config.transformer,
  getTransformOptions: async () => ({
    transform: {
      experimentalImportSupport: false,
      inlineRequires: true,
    },
  }),
};

// Reduce worker count for stability
config.maxWorkers = 2;

module.exports = withNativeWind(config, { input: './global.css' });
EOF

# 4. Create Development Scripts with Better Error Handling
echo -e "${BLUE}📝 Step 4: Creating Enhanced Startup Scripts${NC}"

# Create tunnel script with authentication check
cat > scripts/start-tunnel-safe.sh << 'EOF'
#!/bin/bash
# Set file limits
ulimit -n 65536

echo "🚀 Starting Expo with tunnel (anonymous mode if not logged in)..."

# Clear caches
rm -rf /tmp/metro-* /tmp/react-* 2>/dev/null || true

# Check if logged in
if npx expo whoami >/dev/null 2>&1; then
    echo "✅ Logged in to Expo"
    CONFIG_FLAG=""
else
    echo "⚠️ Not logged in - using anonymous configuration"
    CONFIG_FLAG="--config expo-anonymous.config.js"
fi

# Start with tunnel - handles auth automatically
export EXPO_NO_TELEMETRY=1
export METRO_MAX_WORKERS=2
export EXPO_TUNNEL_SUBDOMAIN=localclubhouse

npx expo start --tunnel --clear $CONFIG_FLAG
EOF

chmod +x scripts/start-tunnel-safe.sh

# Create local development script
cat > scripts/start-local.sh << 'EOF'
#!/bin/bash
# Set file limits
ulimit -n 65536

echo "🚀 Starting Expo in local mode..."

# Clear caches
rm -rf /tmp/metro-* /tmp/react-* 2>/dev/null || true

# Check login status
if ! npx expo whoami >/dev/null 2>&1; then
    echo "⚠️ Not logged in - some features may be limited"
fi

# Start local server
export EXPO_NO_TELEMETRY=1
export METRO_MAX_WORKERS=2
export REACT_NATIVE_PACKAGER_HOSTNAME=$(ipconfig getifaddr en0 || echo "localhost")

echo "📱 Using IP: $REACT_NATIVE_PACKAGER_HOSTNAME"

npx expo start --lan --clear
EOF

chmod +x scripts/start-local.sh

# 5. Update package.json with new scripts
npm pkg set scripts.dev:safe="./scripts/start-tunnel-safe.sh"
npm pkg set scripts.dev:local="./scripts/start-local.sh"
npm pkg set scripts.login="npx expo login"
npm pkg set scripts.logout="npx expo logout"
npm pkg set scripts.whoami="npx expo whoami"

# 6. Create connection test script
echo -e "${BLUE}🔍 Step 5: Creating Connection Test Script${NC}"
cat > scripts/test-connection.sh << 'EOF'
#!/bin/bash

echo "🔍 Testing Expo Connection..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Test Metro bundler
echo "📡 Testing Metro bundler..."
if curl -s http://localhost:8081 >/dev/null 2>&1; then
    echo "✅ Metro bundler is running"
else
    echo "❌ Metro bundler not accessible"
fi

# Test network interfaces
echo ""
echo "🌐 Available network interfaces:"
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "  - " $2}'

# Test Expo status
echo ""
echo "👤 Expo account status:"
if npx expo whoami >/dev/null 2>&1; then
    echo "✅ Logged in as: $(npx expo whoami)"
else
    echo "⚠️ Not logged in (anonymous mode)"
fi

# Check assets
echo ""
echo "📦 Asset status:"
for asset in icon.png splash.png adaptive-icon.png favicon.png; do
    if [ -f "assets/$asset" ]; then
        echo "✅ assets/$asset exists"
    else
        echo "❌ assets/$asset missing"
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
EOF

chmod +x scripts/test-connection.sh

# 7. Final summary and instructions
echo ""
echo -e "${GREEN}✅ ALL FIXES IMPLEMENTED SUCCESSFULLY!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${BLUE}📋 SOLUTIONS IMPLEMENTED:${NC}"
echo "1. ✅ Created missing assets (icon.png, splash.png, etc.)"
echo "2. ✅ Set up anonymous development mode (no login required)"
echo "3. ✅ Optimized Metro config with increased timeouts"
echo "4. ✅ Created safe startup scripts with auth handling"
echo ""
echo -e "${BLUE}🚀 HOW TO START:${NC}"
echo ""
echo -e "${GREEN}Option 1: Tunnel (Most Reliable)${NC}"
echo "  npm run dev:safe"
echo "  - Works without Expo login"
echo "  - Bypasses network issues"
echo "  - Generates public URL"
echo ""
echo -e "${GREEN}Option 2: Local Network${NC}"
echo "  npm run dev:local"
echo "  - Faster than tunnel"
echo "  - Requires same WiFi network"
echo ""
echo -e "${YELLOW}📱 TO LOGIN TO EXPO (Optional):${NC}"
echo "  npm run login"
echo ""
echo -e "${YELLOW}🔍 TO TEST CONNECTION:${NC}"
echo "  ./scripts/test-connection.sh"
echo ""
echo -e "${PURPLE}Ready to start development! 🎉${NC}"